### ISSUE TITLE
StrokeStyles: Dots not painted in D2D backend.

### ISSUE THREAD

**Issue by mity** [mity/windrawlib#12]
@antonioscuri

For some reason, dots are not painted in the D2D backend:

![clipboard01](https://user-images.githubusercontent.com/873269/39075316-5d99d5be-44f5-11e8-894a-c3f3ecae2076.png)

Dotted style implies no painting. The styles mixing dashes and dots paint just the dashes.
Any idea what can be the culprit?

**Comment by antonioscuri** [comment]
Hi,

  Yes, the definition of dotted in D2D is too close of each other. They
merge when line width is 1. If you increase the line width you will see the
dots.

  That was the reason I have too implement the Custom function too. When line
width is 1 I have to define a custom dash of { 2, 2}. I end up defining for
simple dash too. But I think we should respect the default in D2D, so I
implemented that on my side. Sorry I forgot to warn you about that.

Best,
Scuri


2018-04-20 18:49 GMT-03:00 Martin Mitáš <notifications@github.com>:

**Comment by mity** [comment]
>  If you increase the line width you will see the dots. 

Unfortunately, no. This is what I get if I use stroke width 3.0:

![clipboard01](https://user-images.githubusercontent.com/873269/39076410-5d725aec-44fb-11e8-8246-f13b1e774112.png)

**Comment by antonioscuri** [comment]
If you want to redefine the default using custom infernally I don't mind.
Using {2, 2} for dot works perfectly. I use { 9, 6} for simple dash.

Best,
Scuri


Em sex, 20 de abr de 2018 19:32, Martin Mitáš <notifications@github.com>
escreveu:
