### ISSUE TITLE
StrokeStyles: Antialiasing & GDI+ backend

### ISSUE THREAD

**Issue by mity** [mity/windrawlib#13]
@antonioscuri 

With GDI+ backend, anti-aliasing causes bad artifacts, especially with small stroke widths (1.0f):

![bad screenshot](https://user-images.githubusercontent.com/873269/39075531-810d8b02-44f6-11e8-9968-e9790a2a3059.png)

It can be worked around by applying some 0.5f offset corrections, for example for the horizontal lines here, I have added +0.5f to its X coordinates:

![corrected horiz. lines](https://user-images.githubusercontent.com/873269/39075556-a244c9ca-44f6-11e8-8a50-641c1c7819fe.png)

However that can be tricky for some other paint functions, e.g. `wdDrawRectStyled()`: I was not able to paint a square with `wdDrawRect()` where it would help for all its lines at the same time... 

IMHO the ideal case would be, that when painting just horizontal or vertical lines, and using coordinates placing both line ends exactly into pixel grid (i.e. that there are no anti-aliasing needed for solid line), then all the dashes and dots for the default patterns (or ideally even custom ones, if they use just integers in its pattern) would also fit exactly into pixel grid.

Could maybe `GdipGetPenDashOffset()` be used to achieve that? Or any other idea?

**Comment by antonioscuri** [comment]
I will run your sample code to see what's going one, but should be
something similar to the D2D problem I described. In our own GDI+ library,
we ignored the default dashes for line width == 1 and implemented custom
ones.

Best,
Scuri


2018-04-20 19:05 GMT-03:00 Martin Mitáš <notifications@github.com>:
