### ISSUE TITLE
wdBitBltCachedImage() crashes.

### ISSUE THREAD

**Issue by mity** [mity/windrawlib#15]
When using Direct2D backend, calling `wdBitBltCachedImage()` usually result in a crash in `dummy_ID2D1Bitmap_GetPixelSize()`

**Comment by mity** [comment]
The problem is that `ID2D1Bitmap::GetPixelSize()` returns an aggregate type (here, structure composed of two dwords). That seems little bit as a gray zone when it comes to ABI rules so different compilers seem to expect different ways how the result is really returned to the caller.

**Comment by mity** [comment]
@antonioscuri : This should fix the crash you reported to me by e-mail. At least it fixes it for me as tested with new example code `example/cached-image.c` when building with gcc and MSVC 2017.

Can you please verify it fixes it for you too?

**Comment by antonioscuri** [comment]
Hi,

  Yes, it is working here too. I tested under Visual Studio 2013. Thanks.

Best,
Scuri


2018-05-14 15:01 GMT-03:00 Martin Mitáš <notifications@github.com>:
