### ISSUE TITLE
wdDrawString Vertical Center Align (like Button text)

### ISSUE THREAD

**Issue by mrsshr** [mity/windrawlib#3]
![untitled](https://cloud.githubusercontent.com/assets/4264612/16651588/e516c0b0-447f-11e6-809d-cf3026be499b.png)

DirectWrite:
SetParagraphAlignment(DWRITE_PARAGRAPH_ALIGNMENT_CENTER);

but how to implement same feature using GDI+?

**Comment by mity** [comment]
Are you trying to implement support for vertical alignment? 

In GDI+, this can likely be only done manually, i.e. by measuring the text height and then by adjusting the vertical coordinate accordingly.
